version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db           # Use the service name instead of host.docker.internal
      - POSTGRES_DB=postgres
      - POSTGRES_USER=Intern-Project
      - POSTGRES_PASSWORD=Yash214!
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: Intern-Project
      POSTGRES_PASSWORD: Yash214!
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
