services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres_db     
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PYTHONPATH=/app
    restart: always
    networks:
      - bridge

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      DB_HOST: postgres_db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    networks:
      - bridge
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
networks:
  bridge:
    driver: bridge
      
volumes:
  pg_data:
